apiVersion: apps/v1
kind: Deployment
metadata:
	name: customers-service
	namespace: developer
spec:
	replicas: 1
	selector:
		matchLabels:
			app: customers-service
	template:
		metadata:
			labels:
				app: customers-service
		spec:
			containers:
				- name: customers-service
					image: nhanleeq/spring-petclinic-customers-service:main
					ports:
						- containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
	name: customers-service
	namespace: developer
spec:
	selector:
		app: customers-service
	ports:
		- protocol: TCP
			port: 8081
			targetPort: 8081
	type: ClusterIP
