apiVersion: apps/v1
kind: Deployment
metadata:
  name: discovery-server
  namespace: developer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discovery-server
  template:
    metadata:
      labels:
        app: discovery-server
    spec:
      containers:
        - name: discovery-server
          image: nhanleeq/spring-petclinic-discovery-server:main
          ports:
            - containerPort: 8761
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "docker"
---
apiVersion: v1
kind: Service
metadata:
  name: discovery-server
  namespace: developer
spec:
  selector:
    app: discovery-server
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761
  type: ClusterIP