apiVersion: apps/v1
kind: Deployment
metadata:
  name: vets-service
  namespace: developer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vets-service
  template:
    metadata:
      labels:
        app: vets-service
    spec:
      containers:
        - name: vets-service
          image: nhanleeq/spring-petclinic-vets-service:main
          ports:
            - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: vets-service
  namespace: developer
spec:
  selector:
    app: vets-service
  ports:
    - protocol: TCP
      port: 8083
      targetPort: 8083
  type: ClusterIP