apiVersion: apps/v1
kind: Deployment
metadata:
  name: visits-service
  namespace: developer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: visits-service
  template:
    metadata:
      labels:
        app: visits-service
    spec:
      containers:
        - name: visits-service
          image: nhanleeq/spring-petclinic-visits-service:main
          ports:
            - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: visits-service
  namespace: developer
spec:
  selector:
    app: visits-service
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: ClusterIP
